export enum NotificationSetting {
  CAFE_STATUS_PUSH_ENABLED = 'CAFE_STATUS_PUSH_ENABLED',
  MARKETING_PUSH_ENABLED = 'MARKETING_PUSH_ENABLED',
  CAFE_OFFERS_PUSH_ENABLED = 'CAFE_OFFERS_PUSH_ENABLED',
}
