enum Routes {
  // Main
  COMMUNITY_TAB = 'CommunityTab',
  HOME_TAB = 'HomeTab',
  MY_BN_TAB = 'MyBarnesNobleTab',
  MY_BOOKS_TAB = 'MyBooksTab',
  CAFE_TAB = 'CafeTab',
  MY_PROFILE_TAB = 'MyProfileTab',
  SEARCH_TAB = 'SearchTab',
  ROOT = 'Root',
  APP = 'App',
  ONBOARDING = 'OnboardingStack',
  MODAL_LOGIN_SIGNUP = 'LoginSignupModal',
  CART_TAB = 'CartTab',

  // Screens
  ONBOARDING__CHOOSE_CATEGORY = 'Onboarding_ChooseCategory',
  ONBOARDING__WELCOME = 'Onboarding_Welcome',
  ONBOARDING__READ_BOOKS = 'Onboarding_Read_Books',
  ROOT__LOADING = 'Root_Loading',
  COMMUNITY__MAIN = 'Community_Main',
  COMMUNITY__ASK = 'Community_Ask',
  COMMUNITY__QUESTIONS = 'Community_Questions',
  COMMUNITY__QUESTION = 'Community_Question',
  COMMUNITY__CHOOSE_CATEGORIES = 'Community_Choose_Categories',
  COMMUNITY__QUESTIONS_CATEGORIES = 'Community_Questions_Categories',
  COMMUNITY__ANSWER = 'Community_Answer',
  COMMUNITY__COMMENT = 'Community_Comment',
  COMMUNITY__RECOMMENDED_USER = 'Community_Recommended_User',
  HOME__MAIN = 'Home_Main',
  HOME__DISCOVERY = 'Home_Discovery',
  HOME__CATEGORIES = 'Home_Categories',
  HOME__BROWSE = 'Home_Browse',
  HOME__WHATS_NEW = 'Home_Whats_New',
  HOME__STORE_DETAILS = 'Home_StoreDetails',
  MY_BN__STORE_DETAILS = 'MyBarnesNoble_StoreDetails',
  MY_BN__SEARCH_STORE = 'MyBarnesNoble_SearchStore',
  MY_BN__COUPONS = 'MyBarnesNoble_Coupons',
  MY_BN__MEMBERSHIP = 'MyBarnesNoble_Membership',
  MY_BN__EVENTS = 'MyBarnesNoble_Events',
  MY_BN__EVENT_DETAILS = 'MyBarnesNoble_EventDetails',
  CAFE__MAIN = 'Cafe_Main',
  CAFE__MAINTAB = 'Cafe_Main_tab',
  CAFE__CATEGORIES = 'Cafe_Categories',
  CAFE__ITEMS = 'Cafe_Items',
  CAFE__ITEM_OPTIONS = 'Cafe_ItemOptions',
  CAFE__CHECKOUT = 'Cafe_Checkout',
  CAFE__CHECKOUT__MAINTAB = 'Cafe_CheckoutTab',
  MY_BN__ADD_MEMBERSHIP = 'MyBarnesNoble_Add_Membership',
  CAFE__CHOOSE_PAYMENT_CARD = 'Cafe_ChoosePaymentCard',
  CAFE__ADD_PAYMENT_CARD = 'Cafe_AddPaymentCard',
  CAFE__ORDERS = 'Cafe_Orders',
  CAFE__SEARCH_VENUES = 'Cafe_SearchVenues',
  CAFE__STORE_DETAILS = 'Cafe_Store_Details',
  CAFE__EVENT_DETAILS = 'Cafe_Event_Details',
  CART__MAIN = 'Cart_Main',
  CART__GIFT_OPTIONS = 'Cart_Gift_Options',
  CART__CHECKOUT = 'Cart_Checkout',
  CART__ORDERS = 'Cart_Orders',
  CART__SELECT_STORE = 'Cart_Select_Store',
  CART__STORE_DETAILS = 'Cart_Store_Details',
  CART__EVENT_DETAILS = 'Cart_Event_Details',
  CART__VERIFY_ADDRESS = 'Cart_Verify_Address',
  MY_BOOKS__LISTS_AND_COLLECTIONS = 'MyBooks_ListsAndCollections',
  MY_BOOKS__NOOK_LIBRARY = 'MyBooks_NookLibrary',
  MY_BOOKS__COLLECTIONS_LIST = 'MyBooks_CollectionsList',
  MY_BOOKS__ADD_TO_LIST = 'MyBooks_AddToList',
  WELCOME__LOGIN = 'Welcome_Login',

  // Modal Screens
  MODAL__LOGIN = 'Modal_Login',
  MODAL__SIGNUP = 'Modal_Signup',
  MODAL__RESET_PASSWORD = 'Modal_ResetPassword',
  MODAL__COUPON = 'Modal_Coupon',
  // Barcode Scanning
  SEARCH__BARCODE_SCAN = 'Search_BarcodeScan',

  SEARCH__MAIN = 'Search_Main',
  SEARCH__SEARCH = 'Search_Search',

  // Shared screens
  SEARCH__MAIN_LEGACY = 'Search_Main_LEGACY', // legacy
  PROFILE__MAIN = 'Profile_Main',
  PROFILE__MY_PROFILE = 'Profile_MyProfile',
  ACCOUNT_ORDER_DETAILS = 'Account_OrderDetails',
  ACCOUNT_SETTINGS = 'Account_Settings',
  ACCOUNT__GIFT_CARDS = 'Account_GiftCards',
  ACCOUNT__MEMBERSHIP = 'Account_Membership',
  ACCOUNT__NAME = 'Account_Name',
  ACCOUNT__GIFT_CARDS_BALANCE = 'Account_GiftCardsBalance',
  ACCOUNT__EMAIL__ADDRESS = 'Account_EmailAddress',
  ACCOUNT__PHONE__NUMBER = 'Account_PhoneNumber',
  ACCOUNT__NOTIFICATIONS = 'Account_Notifications',
  PASSWORD__RESET__MESSAGE = 'Password_ResetMessage',
  PASSWORD__PASSWORD__ASSISTANT__FORM = 'Password_AssistantForm',
  ACCOUNT__SECURITY__QUESTION = 'Account_SecurityQuestionId',
  ACCOUNT__EXPLICIT__CONTENT__SETTING = 'Account_ExplicitContentSetting',
  PASSWORD__ASSISTANT = 'Password_Assistant',
  ACCOUNT_PAYMENT_METHODS = 'Account_Payment_Methods',
  PROFILE__SETTINGS = 'Profile_Settings',
  PROFILE__EDIT_ABOUT = 'Profile_EditAbout',
  PROFILE__EDIT_GENRE_INTERESTS = 'Profile_EditGenreInterests',
  PROFILE__QA_POSTS = 'Profile_QaPosts',
  PROFILE__FOLLOWING = 'Profile_Following',
  PROFILE__FOLLOWERS = 'Profile_Followers',
  PROFILE__LEGAL = 'Profile_Legal',
  PROFILE__EDIT_PASSWORD = 'Profile_EditPassword',
  PROFILE__ADDRESS_BOOK = 'Profile_AddressBook',

  MY_BOOKS__LIST = 'MyBooks_List',
  MY_BOOKS__READING_STATUS_LIST = 'MyBooks_ReadingStatusList',
  MY_BOOK__ADD_TO_READING_STATUS = 'MyBooks_AddToReadingStatus',
  PROFILE__EDIT_NAME = 'Profile_EditName',
  PROFILE__EDIT_PEN_NAME = 'Profile_EditPenName',
  PDP__MAIN = 'Pdp_Main',
  PDP__READERS_LIST = 'Pdp_ReadersList',
  PDP__RELATED_QUESTIONS_LIST = 'Pdp_RelatedQuestionsList',
  PDP__OVERVIEW = 'Pdp_Overview',
  PDP__PRODUCT_DETAILS = 'Pdp_ProductDetails',
  PDP__PROTECTION_PLAN_DETAILS = 'Pdp_ProtectionPlanDetails',
  PDP__NOOK_DEVICE = 'PDP_NookDeviceSpec',
  PDP__WRITE_REVIEW = 'Pdp_WriteReview',
  PDP__READ_LIST_REVIEWS = 'Pdp_ReadListReviews',
  PDP__READ_ITEM_REVIEW = 'Pdp_ReadItemReview',
  PDP__PRODUCT_IMAGES = 'Pdp_ProductImages',
  PDP__TRACKS = 'Pdp_Tracks',
  PDP__CONTRIBUTORS = 'Pdp_Contributors',
  PDP__TOC = 'Pdp_TableOfContents',
  PDP__SELECT_STORE = 'Pdp_SelectStore',
  PDP__AUTHOR_DETAILS = 'Pdp_AuthorDetails',
  PDP__AUTHOR_SEARCH_RESULTS = 'Pdp_AuthorSearchResults',
  WEBVIEW__WITH_SESSION = 'Webview_WithSession',
  WEBVIEW__PDF = 'Webview_Pdf',

  WISHLIST__MY_LISTS = 'WishLists_MyLists',
  WISHLIST__DETAILS = 'WishLists_Details',

  ACCOUNT__ORDER_HISTORY = '  ACCOUNT__ORDER_HISTORY',
}

// double underscore denotes screen routes

export const AUTH_PRORECTED_ROUTES: string[] = [
  Routes.COMMUNITY__ASK,
  Routes.COMMUNITY__ANSWER,
  Routes.PROFILE__SETTINGS,
  Routes.PROFILE__EDIT_ABOUT,
  Routes.PROFILE__EDIT_GENRE_INTERESTS,
  Routes.PROFILE__EDIT_NAME,
  Routes.PROFILE__EDIT_PEN_NAME,
  Routes.CAFE__MAIN,
  Routes.MY_BN__COUPONS,
  Routes.WISHLIST__MY_LISTS,
  Routes.ACCOUNT_SETTINGS,
  Routes.ACCOUNT__GIFT_CARDS,
  Routes.ACCOUNT__MEMBERSHIP,
  Routes.ACCOUNT__NAME,
  Routes.ACCOUNT__EMAIL__ADDRESS,
  Routes.ACCOUNT__PHONE__NUMBER,
  Routes.ACCOUNT__SECURITY__QUESTION,
  Routes.ACCOUNT__EXPLICIT__CONTENT__SETTING,
  Routes.ACCOUNT_PAYMENT_METHODS,
]

export enum Params {
  EAN = 'ean', // ean's themselves ids by definition
  AUTHOR_DETAILS = 'author_details',
  AUTHOR_NAME = 'author_name',
  PRODUCT = 'product_details',
  MILQ_MEMBER_UID = 'milq_member_uid',
  STORE_ID = 'store_id',
  STORE_NAME = 'store_name',
  EVENT_ID = 'event_id',
  COUPON_ID = 'coupon_id',
  CAFE_CATEGORY_ID = 'cafe_category_id',
  CAFE_ITEM_ID = 'cafe_item_id',
  CAFE_VENUE_ID = 'cafe_venue_id',
  CAFE_TYPE = 'cafe_type',
  QUESTION_ID = 'questionId',
  ANSWER_ID = 'answerId',
  COLLECTION_ID = 'collectionId',
  WEB_ROUTE = 'web_route',
  CATEGORY_ID = 'categoryId',
  SEARCH_TYPE = 'search_type',
  READING_STATUS = 'readingStatus',
  TITLE = 'title',
  USER_TIP = 'user_tip',
  RELOAD_SCREEN = 'reload_screen',
  WORK_ID = 'work_id',
  EDIT_MODE = 'edit_mode',
  PDF_FILE = 'pdf_file',
  CAFE_CURRENT_ORDER_ID = 'cafe_current_order_id',
  STACK = 'stack',
  WISHLIST_ID = 'wishlistId',
  SEARCH_QUERY = 'searchQuery',
  ACCOUNT_ORDER = 'accountOrder',
  BROWSE_URL = 'browseUrl',
  ORDER_ID = 'orderId',
  WEBVIEW_TITLE = 'webview_title',
}

export enum WebRoutes {
  PRODUCT_URL = '/w/<WORK_ID>?ean=<EAN>',

  MEMBERSHIP_MAIN = '/membership',
  MANAGE_MY_MEMBERSHIP = '/mobile/account/manage/memberships/associate-membership.jsp',
  MEMBERSHIP_TERMS = '/h/membership-terms-conditions',

  MEMBERSHIP_TERMS_CONDITIONS = 'https://www.barnesandnoble.com/h/membership-terms-conditions',
  MANAGE_MEMBERSHIP = 'https://www.barnesandnoble.com/account/manage/memberships/associate-membership.jsp',
  MEMBERSHIP_LEARN_MORE = 'https://www.barnesandnoble.com/membership/',
  MEMBERSHIP_LEARN_MORE_MOBILE = 'https://m.barnesandnoble.com/membership/',
  BLOG = 'https://www.barnesandnoble.com/blog/',
  BLOG_MOBILE = 'https://m.barnesandnoble.com/blog/',
  PRESS = 'https://press.barnesandnoble.com/',

  FORGOT_PASSWORD = 'https://m.barnesandnoble.com/account/',
  HELP = 'https://help.barnesandnoble.com/',
  SHOP_GIFT_CARDS = 'https://m.barnesandnoble.com/b/gift-cards/_/N-8rg',
  DIGITAL_RIGHT_REQUEST = 'https://bn.clarip.com/dsr/create?processNonCA=1',
  WEB_BASE = 'https://m.barnesandnoble.com',

  APP_TERMS = 'http://www.nook.com/services/cms/doc/modern/shared/us/EndUserLicenseAgreement.html',
  PRIVACY_POLICY = 'http://www.nook.com/services/cms/doc/modern/shared/us/PrivacyPolicy.html',
  TERMS_OF_USE = 'http://www.nook.com/services/cms/doc/modern/shared/us/TermsAndConditionsOfUse.html',
  DIGITAL_CONTENT = 'http://www.nook.com/services/cms/doc/modern/shared/us/DigitalContentTermsOfSale.html',
  NOOK_PROTECTION_PLAN_TCS = 'http://nook.barnesandnoble.com/u/nook-protection-plan-terms-and-conditions/379003273',
}

export default Routes
