/* eslint-disable global-require */

const IMAGES = {
  library: {
    publicCollection: require('./library/public_collection.png'),
    listGridToggle: require('./library/list_grid_toggle.png'),
  },
  bookStack: require('./graphics/bookStack.png'),
  bookShelf: require('./graphics/bookShelf.png'),
  emptySearch: require('./graphics/EmptySearch.png'),
  coupons: require('./graphics/coupons.png'),
  cafe: require('./graphics/cafe.png'),
  books: require('./graphics/books.png'),
  search: require('./graphics/search.png'),
  starbucks: require('./graphics/starbucks.png'),
  bnCard: require('./graphics/bn.card.png'),
  noComments: require('./graphics/noComments.png'),
  booksellerContent: require('./graphics/bookseller-content.png'),
  emptyInfo: require('./graphics/emptyInfo.png'),
  emptyStoreList: require('./graphics/emptyStoreList.png'),
}

export const nav = {
  scanbar: require('./icons/barcode_scanner.png'),
  tabs: {
    community: require('./nav/tabs/community.png'),
    home: require('./nav/tabs/home.png'),
    books: require('./nav/tabs/books.png'),
    store: require('./nav/tabs/store.png'),
    cafe: require('./nav/tabs/cafe.png'),
    cart: require('./nav/tabs/cart.png'),
    search: require('./nav/tabs/search.png'),
    activeHome: require('./nav/tabs/active-home.png'),
    activeCommunity: require('./nav/tabs/active-community.png'),
    activeStore: require('./nav/tabs/active-store.png'),
    activeBooks: require('./nav/tabs/active-books.png'),
    activeCafe: require('./nav/tabs/active-cafe.png'),
    activeCart: require('./nav/tabs/active-cart.png'),
    activeSearch: require('./nav/tabs/active-search.png'),
  },
  topBar: {
    back: require('./nav/top_bar/back.png'),
    loupe: require('./nav/top_bar/loupe.png'),
    user: require('./nav/top_bar/user.png'),
    dots: require('./nav/top_bar/dots.png'),
    settings: require('./nav/top_bar/settings.png'),
    share: require('./nav/top_bar/share.png'),
  },
}

export const membership = {
  shipping: require('./icons/membership/shipping.png'),
  coupons: require('./icons/membership/coupons.png'),
  bookDeal: require('./icons/membership/book_deal.png'),
  save: require('./icons/membership/save.png'),
  access: require('./icons/membership/access.png'),
  nookDevice: require('./icons/membership/nook_device.png'),
  gift: require('./icons/membership/gift.png'),
  appleWallet: require('./icons/membership/appleWallet.png'),
}

export const cards = {
  amex: require('./icons/cards/amex.png'),
  default: require('./icons/cards/default.png'),
  discover: require('./icons/cards/discover.png'),
  mastercard: require('./icons/cards/mastercard.png'),
  visa: require('./icons/cards/visa.png'),
  membercard: require('./icons/cards/member_card.png'),
  kidsCard: require('./icons/cards/kidsClub_card.png'),
  educatorCard: require('./icons/cards/educator_card.png'),
  employeeCard: require('./icons/cards/employee_card.png'),
}

export const icons = {
  addWishlist: require('./icons/add_wishlist.png'),
  gift: require('./icons/gift.png'),
  edit: require('./icons/edit.png'),
  dots: require('./nav/top_bar/dots.png'),
  store: require('./nav/tabs/store.png'),
  locationPin: require('./icons/location_pin.png'),
  cafe: require('./icons/cafe.png'),
  direction: require('./icons/direction.png'),
  favorite: require('./icons/favorite.png'),
  unfavorite: require('./icons/no-favorite.png'),
  sort: require('./icons/sort.png'),
  expand: require('./icons/expand.png'),
  upload: require('./icons/upload.png'),
  actionInfo: require('./icons/action_info.png'),
  filter: require('./icons/filter.png'),
  forward: require('./icons/forward.png'),
  giftCard: require('./icons/gift_card.png'),
  checkmark: require('./icons/checkmark.png'),
  checkboxChecked: require('./icons/checkbox_checked.png'),
  checkboxCheckedDisabled: require('./icons/checkbox_checked_disabled.png'),
  checkboxCheckedCircle: require('./icons/checkbox_checked_circle.png'),
  checkboxUnchecked: require('./icons/checkbox_unchecked.png'),
  checkboxUncheckedDisabled: require('./icons/checkbox_unchecked_disabled.png'),
  radioSelected: require('./icons/radio_selected.png'),
  radioSelectedDisabled: require('./icons/radio_selected_disabled.png'),
  radioDeselected: require('./icons/radio_deselected.png'),
  radioDeselectedDisabled: require('./icons/radio_deselected_disabled.png'),
  creditCard: require('./icons/credit_card.png'),
  checkout: require('./icons/checkout.png'),
  close: require('./icons/close.png'),
  eyeOn: require('./icons/eyeOn.png'),
  eyeOff: require('./icons/eyeOff.png'),
  error: require('./icons/error.png'),
  findStore: require('./icons/find_store.png'),
  sortDefault: require('./icons/sort_default.png'),
  plus: require('./icons/plus.png'),
  minus: require('./icons/minus.png'),
  minusCart: require('./icons/minusCart.png'),
  myLocation: require('./icons/myLocation.png'),
  add: require('./icons/add.png'),
  lockClosed: require('./icons/lock_closed.png'),
  listView: require('./icons/list_view.png'),
  gridView: require('./icons/grid_view.png'),
  spinner: require('./icons/spinner.png'),
  searchClose: require('./icons/search_close.png'),
  down: require('./icons/down.png'),
  delete: require('./icons/delete.png'),
  settingEdit: require('./icons/setting_edit.png'),
  browser: require('./icons/browser.png'),
  disableNotification: require('./icons/disable_notification.png'),
  enableNotification: require('./icons/enable_notification.png'),
  flag: require('./icons/flag.png'),
  public: require('./icons/public.png'),
  preOrder: require('./icons/preOrder.png'),
  audio: require('./icons/audio.png'),
  share: require('./icons/share.png'),
  uploadProfilePic: require('./icons/buttonPictureUpload.png'),
  actionClose: require('./icons/action_close.png'),
  calendar: require('./icons/calendar.png'),
  tag: require('./icons/tag.png'),
  chevronUp: require('./icons/chevron_up.png'),
  chevronDown: require('./icons/chevron_down.png'),
  xmark: require('./icons/xmark.png'),
  bopisIcon: require('./icons/bopis_icon.png'),
  pinMap: __DEV__
    ? require('./icons/pin_map_dev.png')
    : require('./icons/pin_map_prod.png'),
  pinMapFavorite: __DEV__
    ? require('./icons/pin_map_favorite_dev.png')
    : require('./icons/pin_map_favorite_prod.png'),
  arrowRight: require('./icons/arrow_right.png'),
  emptyStar: require('./icons/emptyStar.png'),
  fullStar: require('./icons/fullStar.png'),
  addCircle: require('./icons/add_circle.png'),
  newList: require('./icons/new_list.png'),
  circleCheckmark: require('./icons/circle_checkmark.png'),
  categories: require('./icons/categories.png'),
  storeInfo: require('./icons/store_info.png'),
}

export const logInImages = {
  lotties: {
    cafe: require('./loginScreen/lotties/Cafe.json'),
    member: require('./loginScreen/lotties/Member.json'),
    shopping: require('./loginScreen/lotties/Shopping.json'),
  },
  images: {
    backgrounds: {
      left: require('./loginScreen/cafe.jpg'),
      middle: require('./loginScreen/member.jpg'),
      right: require('./loginScreen/shopping.jpg'),
    },
    logo: require('./loginScreen/Barnes&Noble.png'),
  },
}

export default IMAGES
