require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

# def default_pods
#   # Comment the next line if you don't want to use dynamic frameworks
#   # use_frameworks!
#   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
#   pod 'React', path: rn_path

# RN 0.6 and above doesn't support manually linked Passkit library => auto-linking required
#   pod 'react-native-passkit-wallet', path: '../node_modules/react-native-passkit-wallet'
# end

# React Native Maps dependencies
#rn_maps_path = '../node_modules/react-native-maps'
#pod 'react-native-google-maps', :path => rn_maps_path
#pod 'GoogleMaps'
##pod 'Google-Maps-iOS-Utils'


target 'BNApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  pod 'react-native-cookies', :path => '../node_modules/@react-native-cookies/cookies'

  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'
end

target 'BNAppEnt' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

end

target 'BNAppEPreProd' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

end


post_install do |installer|
  flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
